[project]
name = "vanadium"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "invoke (>=2.2.0,<3.0.0)",
  "types-invoke (>=2.0.0.10,<3.0.0.0)",
]

[tool.uv]
package = false

[dependency-groups]
build = [
  "pyyaml (>=6.0.2,<7.0.0)",
]
